site_name: Development
docs_dir: .
nav:
  - Home: pages/home.md
  - Contributing: pages/contributing.md
  - PR Guidelines: pages/pull_requests.md
  - DevOps Processes: pages/devops_processes.md
  - CICD Pipelines: pages/cicd_pipelines.md
  - Future Development: pages/future_development.md