site_name: Artifact Docs
docs_dir: docs

plugins:
  - search
  - monorepo

nav:
  - Home: index.md
  - Core: '!include artifact-core/mkdocs.yml'
  - Experiment: '!include artifact-experiment/mkdocs.yml'
  - Torch: '!include artifact-torch/mkdocs.yml'