site_name: Artifact-ML Docs
docs_dir: docs/pages

plugins:
  - search
  - monorepo

nav:
  - Artifact-ML: home.md
  # - artifact-core: '!include artifact-core/mkdocs.yml'
  # - artifact-experiment: '!include artifact-experiment/mkdocs.yml'
  # - artifact-torch: '!include artifact-torch/mkdocs.yml'
  # - DevOps & CICD: '!include .github/mkdocs.yml'