site_name: artifact-experiment
docs_dir: docs
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Architecture: architecture.md
  - Core Entities: core_entities.md
  - Development Guide: development_guide.md