from typing import Dict, List, Protocol


class LabelsSpecProtocol(Protocol):
    @property
    def id_name(self) -> str: ...

    @property
    def ls_labels(self) -> List[str]: ...

    @property
    def n_labels(self) -> int: ...

    @property
    def label_classes_map(self) -> Dict[str, List[str]]: ...

    @property
    def label_classes_count_map(self) -> Dict[str, int]: ...

    def get_classes(self, label_name: str) -> List[str]: ...

    def get_n_classes(self, label_name: str) -> int: ...
