site_name: artifact-core
docs_dir: docs
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Domain Toolkits:
      - Domain Toolkits: domain_toolkits/index.md
      - Table Comparison Toolkit: domain_toolkits/table_comparison_toolkit.md
      - Binary Classification Toolkit: domain_toolkits/binary_classification_toolkit.md
  - Architecture: architecture.md
  - Core Entities: core_entities.md
  - Development Guide: development_guide.md
  - Contributing Artifacts: contributing_artifacts.md