from typing import Protocol, Sequence


class ClassSpecProtocol(Protocol):
    @property
    def label_name(self) -> str: ...

    @property
    def class_names(self) -> Sequence[str]: ...

    @property
    def n_classes(self) -> int: ...

    def __eq__(self, other: object) -> bool: ...

    def get_class_idx(self, class_name: str) -> int: ...

    def has_class(self, class_name: str) -> bool: ...
