site_name: Artifact-ML Docs
docs_dir: .

plugins:
  - search
  - monorepo

nav:
  - Artifact-ML: pages/index.md
  - artifact-core: '!include ../artifact-core/docs/mkdocs.yml'
  - artifact-experiment: '!include ../artifact-experiment/docs/mkdocs.yml'
  - artifact-torch: '!include ../artifact-torch/docs/mkdocs.yml'
  - DevOps & CICD: '!include ../.github/docs/mkdocs.yml'