site_name: Artifact-ML Docs
repo_url: https://github.com/vasileios-ektor-papoulias/artifact-ml
edit_uri: edit/main/

docs_dir: .

theme:
  name: material

  logo: assets/artifact_ml_logo.svg

  favicon: assets/artifact_ml_favicon.ico

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - search.suggest
    - search.highlight

plugins:
  - search
  - monorepo

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Artifact-ML: index.md
  - artifact-core: '!include ../artifact-core/docs/mkdocs.yml'
  - artifact-experiment: '!include ../artifact-experiment/docs/mkdocs.yml'
  - artifact-torch: '!include ../artifact-torch/docs/mkdocs.yml'
  - DevOps & CICD: '!include ../.github/docs/mkdocs.yml'