site_name: Artifact-ML Docs
docs_dir: .
plugins:
  - search
  - monorepo

nav:
  - Artifact-ML: index.md
  - artifact-core: '!include ../artifact-core/docs/mkdocs.yml'
  # - artifact-experiment: '!include artifact-experiment/mkdocs.yml'
  # - artifact-torch: '!include artifact-torch/mkdocs.yml'
  # - DevOps & CICD: '!include .github/mkdocs.yml'