name: CI_MAIN

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  ci_component:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: artifact-core
            module: artifact_core
            flag: core
          - component: artifact-experiment
            module: artifact_experiment
            flag: experiment
          - component: artifact-torch
            module: artifact_torch
            flag: torch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry and Dependencies
        run: |
          cd ${{ matrix.component }}
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --with dev

      - name: Run Linting with Ruff
        run: |
          cd ${{ matrix.component }}
          poetry run ruff check .

      - name: Run Unit Tests with Pytest
        run: |
          cd ${{ matrix.component }}
          poetry run pytest \
            --cov="${{ matrix.module }}" \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ${{ matrix.component }}/coverage.xml
          flags: ${{ matrix.flag }}
          fail_ci_if_error: true

      - name: Build Package
        run: |
          cd ${{ matrix.component }}
          poetry build
