name: CI_MAIN

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  ci_component:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [artifact-core, artifact-experiment, artifact-torch]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry and Dependencies
        run: |
          cd ${{ matrix.component }}
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"
          poetry install

      - name: Run Linting with Ruff
        run: |
          cd ${{ matrix.component }}
          poetry run ruff check .

      - name: Run Unit Tests with Pytest
        run: |
          cd ${{ matrix.component }}
          poetry run pytest

      - name: Build Package
        run: |
          cd ${{ matrix.component }}
          poetry build
