name: CI_TORCH_ON_PUSH

on:
  push:
    branches-ignore:
      - 'main'
      - 'dev-core'
      - 'dev-experiment'
      - 'dev-torch'
    paths:
      - 'artifact-torch**'
  workflow_dispatch:

env:
  COMPONENT: artifact-torch

jobs:
  ci_component:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry and Dependencies
        run: |
          cd ${{ env.COMPONENT }}
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --with dev

      - name: Run Linting with Ruff
        run: |
          cd ${{ env.COMPONENT }}
          poetry run ruff check .

      - name: Run Unit Tests with Pytest
        run: |
          cd ${{ env.COMPONENT }}
          poetry run pytest

      - name: Build Package
        run: |
          cd ${{ env.COMPONENT }}
          poetry build
