name: ENFORCE_BRANCH_NAMING

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  check-branch-naming:
    runs-on: ubuntu-latest
    env:
      ALLOWED_COMPONENTS: "root core experiment torch"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ensure scripts are executable
        run: chmod +x .github/scripts/linting/*.sh
        
      - name: Check branch naming convention
        run: |
          # Run the branch naming check script
          .github/scripts/linting/lint_branch_name.sh "${{ github.head_ref }}" "${{ env.ALLOWED_COMPONENTS }}"
