name: LINT_MERGE_COMMIT_DESCRIPTION

on:
  push:
    branches:
      - main

jobs:
  lint-merge-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Ensure scripts are executable
        run: chmod +x .github/scripts/linting/*.sh
        
      - name: Lint merge commit description if it's a merge commit
        run: |
          # This script will check if it's a merge commit and lint it if it is
          .github/scripts/linting/lint_merge_commit_description.sh
