name: SONAR_PR[DEV_CORE]

on:
  pull_request:
    branches: [ dev-core ]
    paths: [ 'artifact-core/**' ]
  workflow_dispatch: {}

env:
  COMPONENT: artifact-core
  PROJECT_KEY: vasileios-ektor-papoulias_artifact-core

jobs:
  sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install Poetry and Dependencies
        run: |
          cd "$COMPONENT"
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --with dev

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ${{ env.COMPONENT }}
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}